"""Static S&P 500 + NASDAQ 100 ticker-to-company mapping for suggest."""

# fmt: off
TICKERS: dict[str, str] = {
    "AAPL": "Apple", "ABBV": "AbbVie", "ABT": "Abbott", "ACN": "Accenture",
    "ADBE": "Adobe", "ADI": "Analog Devices", "ADM": "Archer Daniels", "ADP": "ADP",
    "ADSK": "Autodesk", "AEP": "American Electric Power", "AES": "AES Corp",
    "AFL": "Aflac", "AIG": "AIG", "AJG": "Arthur J Gallagher", "AKAM": "Akamai",
    "ALB": "Albemarle", "ALGN": "Align Technology", "ALL": "Allstate",
    "AMAT": "Applied Materials", "AMD": "AMD", "AME": "Ametek", "AMGN": "Amgen",
    "AMP": "Ameriprise", "AMT": "American Tower", "AMZN": "Amazon",
    "ANET": "Arista Networks", "ANSS": "Ansys", "AON": "Aon", "APA": "APA Corp",
    "APD": "Air Products", "APH": "Amphenol", "APTV": "Aptiv",
    "ARE": "Alexandria RE", "ASML": "ASML Holdings", "ATO": "Atmos Energy",
    "ATVI": "Activision Blizzard", "AVB": "AvalonBay", "AVGO": "Broadcom",
    "AVY": "Avery Dennison", "AWK": "American Water Works", "AXP": "American Express",
    "AZO": "AutoZone", "BA": "Boeing", "BAC": "Bank of America", "BAX": "Baxter",
    "BBWI": "Bath Body Works", "BBY": "Best Buy", "BDX": "Becton Dickinson",
    "BEN": "Franklin Templeton", "BF.B": "Brown Forman", "BIIB": "Biogen",
    "BIO": "Bio-Rad", "BK": "BNY Mellon", "BKNG": "Booking Holdings",
    "BKR": "Baker Hughes", "BLK": "BlackRock", "BMY": "Bristol Myers",
    "BR": "Broadridge", "BRK.B": "Berkshire Hathaway", "BSX": "Boston Scientific",
    "BWA": "BorgWarner", "BXP": "BXP Inc", "C": "Citigroup", "CAG": "ConAgra",
    "CAH": "Cardinal Health", "CARR": "Carrier Global", "CAT": "Caterpillar",
    "CB": "Chubb", "CBOE": "Cboe Global", "CBRE": "CBRE Group",
    "CCI": "Crown Castle", "CCL": "Carnival", "CDNS": "Cadence Design",
    "CDW": "CDW Corp", "CE": "Celanese", "CEG": "Constellation Energy",
    "CF": "CF Industries", "CFG": "Citizens Financial", "CHD": "Church Dwight",
    "CHRW": "CH Robinson", "CHTR": "Charter Comm", "CI": "Cigna",
    "CINF": "Cincinnati Financial", "CL": "Colgate Palmolive", "CLX": "Clorox",
    "CMA": "Comerica", "CMCSA": "Comcast", "CME": "CME Group", "CMG": "Chipotle",
    "CMI": "Cummins", "CMS": "CMS Energy", "CNC": "Centene", "CNP": "CenterPoint",
    "COF": "Capital One", "COO": "CooperCompanies", "COP": "ConocoPhillips",
    "COST": "Costco", "CPB": "Campbell Soup", "CPRT": "Copart",
    "CPT": "Camden Property", "CRL": "Charles River Labs", "CRM": "Salesforce",
    "CSCO": "Cisco", "CSGP": "CoStar Group", "CSX": "CSX Corp",
    "CTAS": "Cintas", "CTLT": "Catalent", "CTRA": "Coterra Energy",
    "CTSH": "Cognizant", "CTVA": "Corteva", "CVS": "CVS Health",
    "CVX": "Chevron", "CZR": "Caesars Entertainment", "D": "Dominion Energy",
    "DAL": "Delta Air Lines", "DD": "DuPont", "DE": "Deere",
    "DECK": "Deckers Outdoor", "DFS": "Discover Financial", "DG": "Dollar General",
    "DGX": "Quest Diagnostics", "DHI": "DR Horton", "DHR": "Danaher",
    "DIS": "Walt Disney", "DISH": "Dish Network", "DLTR": "Dollar Tree",
    "DOV": "Dover", "DOW": "Dow Inc", "DPZ": "Dominos Pizza",
    "DRI": "Darden Restaurants", "DTE": "DTE Energy", "DUK": "Duke Energy",
    "DVA": "DaVita", "DVN": "Devon Energy", "DXCM": "DexCom",
    "EA": "Electronic Arts", "EBAY": "eBay", "ECL": "Ecolab",
    "ED": "Consolidated Edison", "EFX": "Equifax", "EIX": "Edison Intl",
    "EL": "Estee Lauder", "EMN": "Eastman Chemical", "EMR": "Emerson Electric",
    "ENPH": "Enphase Energy", "EOG": "EOG Resources", "EPAM": "EPAM Systems",
    "EQIX": "Equinix", "EQR": "Equity Residential", "EQT": "EQT Corp",
    "ES": "Eversource", "ESS": "Essex Property", "ETN": "Eaton",
    "ETR": "Entergy", "ETSY": "Etsy", "EVRG": "Evergy",
    "EW": "Edwards Lifesciences", "EXC": "Exelon", "EXPD": "Expeditors",
    "EXPE": "Expedia", "EXR": "Extra Space Storage", "F": "Ford",
    "FANG": "Diamondback Energy", "FAST": "Fastenal", "FBIN": "Fortune Brands",
    "FCX": "Freeport McMoRan", "FDS": "FactSet", "FDX": "FedEx",
    "FE": "FirstEnergy", "FFIV": "F5 Networks", "FIS": "Fidelity National",
    "FISV": "Fiserv", "FITB": "Fifth Third", "FLT": "Fleetcor",
    "FMC": "FMC Corp", "FOX": "Fox Corp", "FOXA": "Fox Corp A",
    "FRC": "First Republic", "FRT": "Federal Realty", "FTNT": "Fortinet",
    "FTV": "Fortive", "GD": "General Dynamics", "GE": "GE Aerospace",
    "GEHC": "GE HealthCare", "GEN": "Gen Digital", "GILD": "Gilead Sciences",
    "GIS": "General Mills", "GL": "Globe Life", "GLW": "Corning",
    "GM": "General Motors", "GNRC": "Generac", "GOOG": "Alphabet",
    "GOOGL": "Alphabet", "GPC": "Genuine Parts", "GPN": "Global Payments",
    "GRMN": "Garmin", "GS": "Goldman Sachs", "GWW": "Grainger",
    "HAL": "Halliburton", "HAS": "Hasbro", "HBAN": "Huntington Bancshares",
    "HCA": "HCA Healthcare", "HD": "Home Depot", "HOLX": "Hologic",
    "HON": "Honeywell", "HPE": "Hewlett Packard Enterprise", "HPQ": "HP Inc",
    "HRL": "Hormel Foods", "HSIC": "Henry Schein", "HST": "Host Hotels",
    "HSY": "Hershey", "HUBB": "Hubbell", "HUM": "Humana",
    "HWM": "Howmet Aerospace", "IBM": "IBM", "ICE": "Intercontinental Exchange",
    "IDXX": "Idexx Labs", "IEX": "Idex Corp", "IFF": "IFF",
    "ILMN": "Illumina", "INCY": "Incyte", "INTC": "Intel",
    "INTU": "Intuit", "INVH": "Invitation Homes", "IP": "International Paper",
    "IPG": "Interpublic", "IQV": "IQVIA", "IR": "Ingersoll Rand",
    "IRM": "Iron Mountain", "ISRG": "Intuitive Surgical", "IT": "Gartner",
    "ITW": "Illinois Tool Works", "IVZ": "Invesco", "J": "Jacobs Solutions",
    "JBHT": "JB Hunt", "JCI": "Johnson Controls", "JKHY": "Jack Henry",
    "JNJ": "Johnson Johnson", "JNPR": "Juniper Networks", "JPM": "JPMorgan Chase",
    "K": "Kellanova", "KDP": "Keurig Dr Pepper", "KEY": "KeyCorp",
    "KEYS": "Keysight", "KHC": "Kraft Heinz", "KIM": "Kimco Realty",
    "KLAC": "KLA Corp", "KMB": "Kimberly Clark", "KMI": "Kinder Morgan",
    "KMX": "CarMax", "KO": "Coca Cola", "KR": "Kroger",
    "L": "Loews", "LDOS": "Leidos", "LEN": "Lennar",
    "LH": "Labcorp", "LHX": "L3Harris", "LIN": "Linde",
    "LKQ": "LKQ Corp", "LLY": "Eli Lilly", "LMT": "Lockheed Martin",
    "LNT": "Alliant Energy", "LOW": "Lowes", "LRCX": "Lam Research",
    "LULU": "Lululemon", "LUV": "Southwest Airlines", "LVS": "Las Vegas Sands",
    "LW": "Lamb Weston", "LYB": "LyondellBasell", "LYV": "Live Nation",
    "MA": "Mastercard", "MAA": "Mid America Apartment", "MAR": "Marriott",
    "MAS": "Masco", "MCD": "McDonalds", "MCHP": "Microchip Technology",
    "MCK": "McKesson", "MCO": "Moodys", "MDLZ": "Mondelez",
    "MDT": "Medtronic", "MET": "MetLife", "META": "Meta Platforms",
    "MGM": "MGM Resorts", "MHK": "Mohawk Industries", "MKC": "McCormick",
    "MKTX": "MarketAxess", "MLM": "Martin Marietta", "MMC": "Marsh McLennan",
    "MMM": "3M", "MNST": "Monster Beverage", "MO": "Altria",
    "MOH": "Molina Healthcare", "MOS": "Mosaic", "MPC": "Marathon Petroleum",
    "MPWR": "Monolithic Power", "MRK": "Merck", "MRNA": "Moderna",
    "MRO": "Marathon Oil", "MS": "Morgan Stanley", "MSCI": "MSCI",
    "MSFT": "Microsoft", "MSI": "Motorola Solutions", "MTB": "MT Bank",
    "MTCH": "Match Group", "MTD": "Mettler Toledo", "MU": "Micron",
    "NCLH": "Norwegian Cruise", "NDAQ": "Nasdaq Inc", "NDSN": "Nordson",
    "NEE": "NextEra Energy", "NEM": "Newmont", "NFLX": "Netflix",
    "NI": "NiSource", "NKE": "Nike", "NOC": "Northrop Grumman",
    "NOW": "ServiceNow", "NRG": "NRG Energy", "NSC": "Norfolk Southern",
    "NTAP": "NetApp", "NTRS": "Northern Trust", "NUE": "Nucor",
    "NVDA": "Nvidia", "NVR": "NVR Inc", "NWL": "Newell Brands",
    "NWS": "News Corp", "NWSA": "News Corp A", "NXPI": "NXP Semiconductors",
    "O": "Realty Income", "ODFL": "Old Dominion Freight", "OGN": "Organon",
    "OKE": "Oneok", "OMC": "Omnicom", "ON": "ON Semiconductor",
    "ORCL": "Oracle", "ORLY": "OReilly Auto", "OTIS": "Otis Worldwide",
    "OXY": "Occidental Petroleum", "PANW": "Palo Alto Networks",
    "PARA": "Paramount Global", "PAYC": "Paycom", "PAYX": "Paychex",
    "PCAR": "Paccar", "PCG": "PG&E", "PDD": "PDD Holdings",
    "PEAK": "Healthpeak", "PEG": "PSEG", "PEP": "PepsiCo",
    "PFE": "Pfizer", "PFG": "Principal Financial", "PG": "Procter Gamble",
    "PGR": "Progressive", "PH": "Parker Hannifin", "PHM": "PulteGroup",
    "PKG": "Packaging Corp", "PLD": "Prologis", "PM": "Philip Morris",
    "PNC": "PNC Financial", "PNR": "Pentair", "PNW": "Pinnacle West",
    "POOL": "Pool Corp", "PPG": "PPG Industries", "PPL": "PPL Corp",
    "PRU": "Prudential", "PSA": "Public Storage", "PSX": "Phillips 66",
    "PTC": "PTC Inc", "PVH": "PVH Corp", "PWR": "Quanta Services",
    "PXD": "Pioneer Natural", "PYPL": "PayPal", "QCOM": "Qualcomm",
    "QRVO": "Qorvo", "RCL": "Royal Caribbean", "RE": "Everest Re",
    "REG": "Regency Centers", "REGN": "Regeneron", "RF": "Regions Financial",
    "RHI": "Robert Half", "RJF": "Raymond James", "RL": "Ralph Lauren",
    "RMD": "ResMed", "ROK": "Rockwell Automation", "ROL": "Rollins",
    "ROP": "Roper Technologies", "ROST": "Ross Stores", "RSG": "Republic Services",
    "RTX": "RTX Corp", "SBAC": "SBA Communications", "SBNY": "Signature Bank",
    "SBUX": "Starbucks", "SCHW": "Charles Schwab", "SEE": "Sealed Air",
    "SHW": "Sherwin Williams", "SIVB": "SVB Financial", "SJM": "JM Smucker",
    "SLB": "Schlumberger", "SNA": "Snap On", "SNPS": "Synopsys",
    "SO": "Southern Company", "SPG": "Simon Property", "SPGI": "SP Global",
    "SRE": "Sempra", "STE": "Steris", "STT": "State Street",
    "STX": "Seagate", "STZ": "Constellation Brands", "SWK": "Stanley Black Decker",
    "SWKS": "Skyworks", "SYF": "Synchrony", "SYK": "Stryker",
    "SYY": "Sysco", "T": "ATT", "TAP": "Molson Coors",
    "TDG": "TransDigm", "TDY": "Teledyne", "TEAM": "Atlassian",
    "TECH": "Bio Techne", "TEL": "TE Connectivity", "TER": "Teradyne",
    "TFC": "Truist", "TFX": "Teleflex", "TGT": "Target",
    "TJX": "TJX Companies", "TMO": "Thermo Fisher", "TMUS": "T-Mobile",
    "TPR": "Tapestry", "TRGP": "Targa Resources", "TRMB": "Trimble",
    "TROW": "T Rowe Price", "TRV": "Travelers", "TSCO": "Tractor Supply",
    "TSLA": "Tesla", "TSN": "Tyson Foods", "TT": "Trane Technologies",
    "TTWO": "Take Two", "TXN": "Texas Instruments", "TXT": "Textron",
    "TYL": "Tyler Technologies", "UAL": "United Airlines", "UDR": "UDR Inc",
    "UHS": "Universal Health", "ULTA": "Ulta Beauty", "UNH": "UnitedHealth",
    "UNP": "Union Pacific", "UPS": "UPS", "URI": "United Rentals",
    "USB": "US Bancorp", "V": "Visa", "VFC": "VF Corp",
    "VICI": "Vici Properties", "VLO": "Valero", "VMC": "Vulcan Materials",
    "VRSK": "Verisk", "VRSN": "VeriSign", "VRTX": "Vertex Pharma",
    "VTR": "Ventas", "VTRS": "Viatris", "VZ": "Verizon",
    "WAB": "Westinghouse Air Brake", "WAT": "Waters Corp", "WBA": "Walgreens",
    "WBD": "Warner Bros Discovery", "WDC": "Western Digital", "WEC": "WEC Energy",
    "WELL": "Welltower", "WFC": "Wells Fargo", "WHR": "Whirlpool",
    "WM": "Waste Management", "WMB": "Williams Companies", "WMT": "Walmart",
    "WRB": "WR Berkley", "WRK": "WestRock", "WST": "West Pharma",
    "WTW": "Willis Towers Watson", "WY": "Weyerhaeuser", "WYNN": "Wynn Resorts",
    "XEL": "Xcel Energy", "XOM": "Exxon Mobil", "XRAY": "Dentsply Sirona",
    "XYL": "Xylem", "YUM": "Yum Brands", "ZBH": "Zimmer Biomet",
    "ZBRA": "Zebra Technologies", "ZION": "Zions Bancorp", "ZTS": "Zoetis",
    # NASDAQ 100 additions not in S&P 500
    "AEP": "American Electric Power", "ABNB": "Airbnb", "ARM": "Arm Holdings",
    "BIDU": "Baidu", "COIN": "Coinbase", "CRWD": "CrowdStrike",
    "CSCO": "Cisco", "DASH": "DoorDash", "DDOG": "Datadog",
    "DLTR": "Dollar Tree", "FANG": "Diamondback Energy", "FAST": "Fastenal",
    "FTNT": "Fortinet", "GFS": "GlobalFoundries", "GRAB": "Grab Holdings",
    "HOOD": "Robinhood", "ICLR": "Icon PLC", "JD": "JD.com",
    "KHC": "Kraft Heinz", "LCID": "Lucid Group", "LRCX": "Lam Research",
    "MELI": "MercadoLibre", "MDB": "MongoDB", "MRVL": "Marvell Technology",
    "NTES": "NetEase", "OKTA": "Okta", "PANW": "Palo Alto Networks",
    "PDD": "PDD Holdings", "PLTR": "Palantir", "RIVN": "Rivian",
    "ROKU": "Roku", "SHOP": "Shopify", "SMCI": "Super Micro Computer",
    "SNOW": "Snowflake", "SPLK": "Splunk", "SQ": "Block Inc",
    "TTD": "Trade Desk", "VEEV": "Veeva Systems", "WDAY": "Workday",
    "ZM": "Zoom Video", "ZS": "Zscaler",
}
# fmt: on
